"""-

Revision ID: 1606d3f599d7
Revises: 6fb97f5cc6d7
Create Date: 2025-02-02 13:46:48.939217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1606d3f599d7'
down_revision = '6fb97f5cc6d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
