"""Initial revision

Revision ID: 347351c66fd1
Revises: 9ff66b4ff8b0
Create Date: 2025-02-02 14:37:07.781431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347351c66fd1'
down_revision = '9ff66b4ff8b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
