"""test

Revision ID: 75539313c1e5
Revises: f0d4811ef5dd
Create Date: 2025-04-13 12:06:56.306911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75539313c1e5'
down_revision = 'f0d4811ef5dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
